"""Carnet 038 (Livre 38, 1–12 August 1875) — reviewer C."""
from fixlib5 import *


def rep(X, c, d, pairs, why):
    t = X.get_new(c, d)['french']
    for a, b in pairs:
        assert a in t, (c, d, a)
        t = t.replace(a, b)
    X.edit_new(c, d, why, french=t)


def fix(X):
    c = '038'
    # Cross-carnet move 038.0290–0320 (Vendredi 13 août) → 039: accepted. The docx has the Livre 39 title page
    # (¶3960–3962, «depuis le vendredi 13 août 1875») before the date line ¶3963; the redirect 038/1875-08-13 →
    # 039/1875-08-13 is generated by the tool from the paragraph move.
    log(c, 'moved', '038.0290–0320 (13 Aug) → 039 accepted: Livre 39 title page precedes the day in the docx')

    # 4 August: Marie's verse epistle to her aunt (title + poem), sent as a letter («j'envoie ceci à ma tante»)
    # (not `> `-quoted: the fr tree holds 038.0131 as a multi-line %% block, which set_french cannot replace)
    for oid in ('038.0130', '038.0131'):
        X.kind(oid, 'letter', "verse epistle Marie sent to her aunt («j'envoie ceci à ma tante»); left unquoted because "
               "fr has a multi-line %% block for 038.0131", source="Épître en vers de Marie à sa tante, 4 août 1875")

    # 8 August (new day, wholly missing from _original): OCR / printed-edition repairs
    rep(X, c, 3846, [('moi-méme', 'moi-même')], 'OCR «méme» → «même»')
    rep(X, c, 3853, [('Je regette', 'Je regrette')], 'printed-edition typo «regette» corrected')
    rep(X, c, 3858, [('*patouchi*1 lampe', '*patouchi* lampe')], 'printed footnote marker «1» removed')
    rep(X, c, 3862, [("je dis qu'il *me plaît*", "je dis qu'il *me plaît beaucoup, le jeune Emile*.")],
        'sentence split by a page break: rejoined with its end (¶3865); printed footnote ¶3863 dropped')
    X.edit_new(c, 3862, rsr=rsr(3862, 3865, 'The printed footnote ¶3863 («Patouchi veut dire éteins en russe», N.d.T.) is left out.'))
    X.drop_new(c, 3863, "printed-edition translator's footnote (N.d.T.) on «patouchi», not Marie's text")
    X.drop_new(c, 3865, 'end of the sentence of ¶3862 (page break), joined there')
    rep(X, c, 3869, [('au livre 1 5ême- Il est', 'au livre 15ème. Il est')], 'OCR split digits and «-» for «.» repaired')
    # 9 August (new day)
    rep(X, c, 3873, [("♦Et pas d'Audiffret*", "*Et pas d'Audiffret*")], 'OCR «♦» for the italic marker')
