import json, os, re, collections
from paths import REPORT, TODAY, work
G = json.load(open(work('gaps.json')))
D = json.load(open(work('scored.json')))
MIS = json.load(open(work('misplaced.json')))

def strongM_between(tome, a, b):
    n = 0
    for r in D['tomes'][str(tome)]:
        if a < r['i'] < b and r['cls'] == 'text' and r.get('cont', 0) >= 0.5 and r.get('nw', 0) >= 8:
            n += 1
    return n

body = [g for g in G['gaps'] if g['region'] == 'body']
sig = [g for g in body if g['n_paras'] > 1 or g['chars'] > 300]

# zones: merge runs in same tome+carnet separated by <=3 strong matches
zones = []
for g in sorted(body, key=lambda g: (g['tome'], g['docx_start'])):
    if zones and zones[-1]['tome'] == g['tome'] and zones[-1]['carnet'] == g['carnet'] \
            and strongM_between(g['tome'], zones[-1]['docx_end'], g['docx_start']) <= 3:
        z = zones[-1]
        z['docx_end'] = g['docx_end']; z['n_paras'] += g['n_paras']; z['chars'] += g['chars']; z['runs'] += 1
        z['heads'] += g['heads_inside']; z['next_match'] = g['next_match']
    else:
        zones.append({'tome': g['tome'], 'carnet': g['carnet'], 'docx_start': g['docx_start'], 'docx_end': g['docx_end'],
                      'n_paras': g['n_paras'], 'chars': g['chars'], 'runs': 1, 'date_heading': g['date_heading'],
                      'heads': list(g['heads_inside']), 'prev_match': g['prev_match'], 'next_match': g['next_match'],
                      'first': g['first']})
zones_sig = [z for z in zones if z['n_paras'] > 1 or z['chars'] > 300]

pc = G['percarnet']
bycar = collections.defaultdict(list)
for g in sig:
    bycar[g['carnet']].append(g)
zbycar = collections.defaultdict(list)
for z in zones_sig:
    zbycar[z['carnet']].append(z)

tome_of = {}
for c in pc:
    pass
RANGES = {1:(0,7),2:(8,14),3:(15,20),4:(21,30),5:(31,44),6:(45,52),7:(53,59),8:(60,64),9:(65,68),10:(69,74),11:(75,80),12:(81,84),13:(85,89),14:(90,94),15:(95,100),16:(101,106)}
for t, (a, b) in RANGES.items():
    for x in range(a, b + 1):
        tome_of[f'{x:03d}'] = t

def clean(s, n=80):
    s = re.sub(r'\s+', ' ', s or '').replace('|', '/')
    return s[:n]

def hd(h):
    return clean(h, 40) if h else '—'

def anchor(m):
    if not m:
        return '—'
    return f"{m['pid']} ({m['file']})"

L = []
A = L.append
tot_u = sum(v.get('unmatched', 0) for c, v in pc.items() if c != '000')
tot_uc = sum(v.get('unmatched_chars', 0) for c, v in pc.items() if c != '000')
tot_p = sum(v.get('tome_paras', 0) for c, v in pc.items() if c != '000')
tot_pc = sum(v.get('tome_chars', 0) for c, v in pc.items() if c != '000')
sig_u = sum(g['n_paras'] for g in sig if g['carnet'] != '000')
sig_c = sum(g['chars'] for g in sig if g['carnet'] != '000')

A(f'# Source completeness: tomes vs content/_original — {TODAY}')
A('')
A('Generated by `just source-completeness`. Read-only analysis; nothing in `content/` was changed.')
A('')
A('## Headline')
A('')
A(f'- Tome body text paragraphs (carnets 001–106): **{tot_p:,}** ({tot_pc:,} chars).')
A(f'- Paragraphs with no match in `_original`: **{tot_u:,}** ({tot_uc:,} chars, {100*tot_uc/tot_pc:.1f}% of tome text).')
A(f'- Of these, **{sig_u:,} paragraphs / {sig_c:,} chars** sit in {len([g for g in sig if g["carnet"]!="000"])} reportable gaps (runs of >1 paragraph, or single paragraphs over 300 chars). These merge into {len([z for z in zones_sig if z["carnet"]!="000"])} gap zones.')
A(f'- The rest ({tot_u - sig_u:,} paras, {tot_uc - sig_c:,} chars) are isolated short lines. Most are dialogue lines and page-break fragments; see the false-positives section.')
A('')
A('## Method')
A('')
A('1. **Tomes.** `content/_raw/tome01–16.docx` were dumped with python-docx (`uv run --with python-docx`), one record per `Document.paragraphs` entry. **"docx N" is that 0-based paragraph index**, the same convention as `english-placeholders-2026-09-26.md`. Styles `Header or footer`, `Table of contents` and `Picture caption`, plus bare page numbers, were dropped. Date headings (weekday + digit) and `Livre/Carnet/Cahier` headings were classed as headings, not text.')
A('2. **Body region.** It runs from the first strong match to the line before `INDEX ALPHABETIQUE` / `TABLE DES MATIERES` / the death note (tome 16). The front matter (introduction, genealogy, editorial notes) and the back matter (index, notes) are excluded from the counts.')
A('3. **_original.** Every `content/_original/CCC/*.md` (000–106, README excluded) was read. Frontmatter, every `%% … %%` span (multi-line too), `#` headings, `[//]: #` lines, footnote definitions and footnote refs were stripped. Text was grouped by paragraph ID.')
A('4. **Normalisation.** Ligatures were expanded, accents stripped (100 is accent-stripped in `_original`), text lowercased, and every non-alphanumeric run collapsed to a space. OCR-split digits (`1 876`) were rejoined.')
A('5. **Matching.** Matching uses word 5-gram shingle containment against a global index of all `_original` text, so matching ignores dates and file placement.')
A('   - A tome paragraph is **matched** if ≥50% of its 5-grams occur in `_original`, **partial** if 20–50%, and **unmatched** if under 20%.')
A('   - Paragraphs under 5 words need an exact normalised substring hit.')
A('   - Paragraphs under 8 words that match, and paragraphs under 15 words at 20–50%, are "weak": they neither count as a gap nor break one, so a stray `- Oui.` found elsewhere does not split a gap.')
A('6. **Gaps.** A gap is a maximal run of unmatched paragraphs; headings and empty lines inside it are absorbed. Char counts are unmatched text paragraphs only; headings and weak lines are excluded.')
A('   - Each gap is assigned to a carnet by its nearest strong-match anchors (previous and next matched paragraph with ≥8 words), cross-checked against the tome\'s `Livre NN` headings.')
A('   - "Zones" merge runs of the same carnet that are separated by 3 or fewer matched paragraphs.')
A('7. **Sanity checks.**')
A('   - Unmatched paragraphs (≥12 words) were re-scored with word 3-grams against their carnet ±1: 95% score below 0.35 and none reach 0.75, so they are not reworded copies.')
A('   - A reverse pass checked for text sitting in a far-away carnet (below).')
A('   - The known gaps from the placeholder report all reappear.')
A('')
A(f'Work files: `{work("")}` — `tomes.json` (docx dump), `scored.json` (per-paragraph containment), **`gaps.json`** (machine-readable: `gaps[]` with `tome`, `docx_start`, `docx_end`, `docx_indices`, `carnet`, `date_heading`, `heads_inside`, `prev_match`/`next_match` anchors, `chars`, `flags`; plus `partials[]` and `percarnet`), `zones.json`, `misplaced.json`, `fp3.json`.')
A('')
A('## Summary per carnet (sorted by unmatched chars)')
A('')
A('Counts are tome body text paragraphs assigned to the carnet. "Gaps" counts reportable runs (>1 para or >300 chars). The last column is the biggest zone.')
A('')
A('| Carnet | Tome | Tome paras | Matched | Partial | Unmatched | Unmatched chars | % of chars | Gaps | Largest zone (docx, paras/chars) |')
A('|---|---|---|---|---|---|---|---|---|---|')
rows = []
for c, v in pc.items():
    if c in ('000', '???'):
        continue
    rows.append((v.get('unmatched_chars', 0), c, v))
rows.sort(reverse=True)
for uc, c, v in rows:
    zs = sorted(zbycar.get(c, []), key=lambda z: -z['chars'])
    big = f"{zs[0]['docx_start']}–{zs[0]['docx_end']} ({zs[0]['n_paras']}/{zs[0]['chars']:,})" if zs else '—'
    pct = 100 * uc / max(1, v.get('tome_chars', 1))
    A(f"| {c} | {tome_of.get(c,'?'):02d} | {v.get('tome_paras',0)} | {v.get('matched',0)} | {v.get('partial',0)} | {v.get('unmatched',0)} | {uc:,} | {pct:.1f}% | {len(bycar.get(c,[]))} | {big} |")
A('')
A('## Top 40 gap zones')
A('')
A('| # | Carnet | Tome | docx range | Paras | Chars | Starts under heading | After (_original) | Before (_original) | First words |')
A('|---|---|---|---|---|---|---|---|---|---|')
for n, z in enumerate(sorted([z for z in zones_sig if z['carnet'] != '000'], key=lambda z: -z['chars'])[:40], 1):
    A(f"| {n} | {z['carnet']} | {z['tome']:02d} | {z['docx_start']}–{z['docx_end']} | {z['n_paras']} | {z['chars']:,} | {hd(z['date_heading'])} | {anchor(z['prev_match'])} | {anchor(z['next_match'])} | {clean(z['first'],60)} |")
A('')

# misplaced
A('## Text present only in a distant carnet')
A('')
A('These tome paragraphs match strongly, but only in a carnet outside the tome\'s range (±1). All of them are small. Most are Marie\'s recurring formulas (`H[is] G[race] t[he] D[uke]…`), stock phrases, or the preface quoted in 000. **No large misplaced block was found**: the gaps below are text that is truly absent, not text moved elsewhere.')
A('')
for o in MIS:
    if o['chars'] > 300 or o['n'] > 1:
        A(f"- tome{o['tome']:02d} docx {o['docx_start']}–{o['docx_end']} ({o['n']} p, {o['chars']} ch) → found in {o['orig_carnet']} {', '.join(o['orig_files'][:2])} ({o['pids'][0]}): «{clean(o['first'],60)}»")
A('')

# false positives
A('## Possible false positives / needs human look')
A('')
A('- **Isolated short lines.** Single unmatched paragraphs under 300 chars are left out of the detailed list. They are mostly one-line dialogue turns, page-break fragments (docx splits a sentence at a page end), marginal OCR scraps, and `[Bas de page déchiré]`-type notes. Their paragraph lists are in `gaps.json`.')
A('- **Notebook title pages.** Examples: `Livre 67ème depuis le jeudi 12 octobre…`, and the `depuis le … jusqu\'au …` lines at the start of 066/072/096. `_original` usually omits these, although 105.0809 now carries one.')
A('- **Newspaper clippings, letters, cover pages, editor notes.** Since the owner decision of 2026-09-27 all of these belong in `_original` (as `kind:` paragraphs, docs/REBUILD_CARNET.md), so they count as missing. Rows flagged `clipping?` or `editorial?` are the likely ones; `just rebuild-draft-plan CCC` classifies them.')
A('- **Editor notes inside the body.** Page notes such as `[page cancellée : p. 182 du manuscrit]` or lists on a notebook cover sit between diary paragraphs. The flags `editorial?`, `clipping?`, `bracketed/rayé` and `short-only` on the gap rows below are heuristic.')
A('- **`[Rayé: …]` / `[Dans la marge: …]` / `[En travers: …]`.** Normalisation drops the brackets and keeps the words, so a struck passage that `_original` carries in bracket form still matches. A bracketed gap therefore means `_original` lacks the words altogether. `_original` may have dropped some struck passages on purpose; check the rows flagged `bracketed/rayé`.')
A('- **Partial paragraphs.** These are present but cut: 20–50% containment, or 50–80% and over 400 chars. They are not in the gap list; they are in `partials` in `gaps.json`. The biggest, by estimated missing chars:')
for p in sorted(G['partials'], key=lambda p: -p['est_missing_chars'])[:25]:
    A(f"  - tome{p['tome']:02d} docx {p['docx']} ({p['carnet']}, {hd(p['head'])}): {p['len']} ch, containment {p['cont']}, ~{p['est_missing_chars']} ch missing — «{clean(p['first'],60)}»")
A('- **Carnet attribution at Livre boundaries.** Where a tome lacks a `Livre NN` heading, attribution relies only on the neighbouring matched paragraphs; the `After`/`Before` anchors are authoritative.')
A('- **Wrong-day placement is out of scope.** The `heading-date-sweep` report covers text that is present but under the wrong day. This report only asks whether the text is present at all.')
A('')

A('## Detailed gap list per carnet')
A('')
A('One row per run: runs of >1 unmatched paragraph, or single paragraphs >300 chars. `docx` is the python-docx paragraph index in `content/_raw/tomeNN.docx`; the range is inclusive and may include headings and empty lines. The exact unmatched paragraph list for each row is in `gaps.json` (`docx_indices`). "After" and "Before" are the `_original` paragraph IDs of the nearest matched text on each side: the insertion point.')
A('')
for c in sorted(bycar):
    if c in ('000',):
        continue
    gs = sorted(bycar[c], key=lambda g: (g['tome'], g['docx_start']))
    tp = sum(g['n_paras'] for g in gs); tc = sum(g['chars'] for g in gs)
    A(f"### {c} — {len(gs)} gaps, {tp} paras, {tc:,} chars")
    A('')
    A('| Tome | docx | Paras | Chars | Under heading (docx) | Headings inside | After | Before | First ~80 chars | Flags |')
    A('|---|---|---|---|---|---|---|---|---|---|')
    for g in gs:
        hi = '; '.join(clean(h, 30) for h in g['heads_inside'][:6]) + (f' (+{len(g["heads_inside"])-6})' if len(g['heads_inside']) > 6 else '')
        A(f"| {g['tome']:02d} | {g['docx_start']}–{g['docx_end']} | {g['n_paras']} | {g['chars']:,} | {hd(g['date_heading'])} ({g['date_heading_docx']}) | {hi or '—'} | {anchor(g['prev_match'])} | {anchor(g['next_match'])} | {clean(g['first'])} | {', '.join(g['flags']) or ''} |")
    A('')

open(REPORT, 'w').write('\n'.join(L) + '\n')
json.dump(zones, open(work('zones.json'), 'w'), ensure_ascii=False, indent=1)
print('rows', len(L))
top = sorted([z for z in zones_sig if z['carnet'] != '000'], key=lambda z: -z['chars'])[:15]
for z in top:
    print(z['carnet'], z['tome'], z['docx_start'], z['docx_end'], z['n_paras'], z['chars'], hd(z['date_heading']), '->', (z['heads'][-1] if z['heads'] else ''))
print(tot_p, tot_u, tot_uc, sig_u, sig_c, len(sig), len(zones_sig))
